mods = ( 
'-- retirado interfiere con mapgen, mg villages',
'-- retirado no util at all dreambuilderhotbar',
'--- problemas con skin  tempsurvive',
'---- retirado no es necesario alchemy + player monoid reistalado y stamina',
'---retirado no util placeablebucket',
'3darmor',
'ambiuence: Genera Muy buenos ambientes en los diferentes biomas existentes',
'animalia: Genera diversos tipos de animales domesticos y fauna silvestre',
'animal world: Genera una gran cantidad de animales salvajes en los biomas indomitos',
'anvil: Util para reparar herramientas rapidamente',
'auroras: Genera Hermosos patrones en el cielo de los biomas glaciares y Nevados',
'astral:',
'awards: Clasico Menu de logros y objetivos',
'ballonblocks',
'--- pensando en utilidad bank account',
'currency',
'beautifulflowers', 
'bonemeal',
'chesse',
'climate',
'creature',
'deathcetro',
'draconis',
'findbiome',
'flying carpet',
'goblins',
'hudbars + hudhunger',
'i3',
'iluminacion',
'inillib idiomas',
'lavastuff',
'magicalities',
'magmaconducts',
'mana',
'mobs',
'modlib',
'moreblock',
'moretrees',
'native village',
'naturalbiomes',
'nettle',
'obsidianstuff',
'orbs dof time  (modificado por mi)',
'people',
'rainbarrel',
'replacer',
'rocks  ---aun no encuentro generadas por mapgen',
'ropes',
'saltdv',
'screwdriver2',
'skelleton',
'skindb',
'snowdrift',
'spiradilus',
'terraform',
'tombs --- esperando encontrar la solucion',
'vector3',
'void chest',
'waterlife',
'wisp',
'witches',
'worldedit',
'xocean',
'areas',
'deathlist',
'-- no funciona. abandonado elepower',
'protector'
'melterns ---- averiguar sobre el mod',
'-- no era lo que buscaba lockworshop',
'sumpf swamp',
'techage',
'--- terribles sonidos snowsong sonidos',
'mtc_chisel',
'bulletin board',
'calendar',
'calendar notes',
'farming',
'flowerpot',
'regrow',
'crafting bench',
'drawers',
'-- tt tooltips se activa con modname tooltip',
'teleport pad',
'random teleport',
'new campfire',
'door',
'comodity market',
'comodity market fantasy',
'airtank',
'cloaking',
'sounding_line',
'halloween',
'unique ores',
'instant ores',
'ediblestuff',
'chocolate stff',
'hbuarmor',
'hudtimers',
'--- retirado, genera errores y no me convencen tmw_slimes',
'dfwarfs caverns',
'--- retirado ya que interfiere con skins y GUI clasess de razas',
'nether',
'living nether',
'funtion delayer',
'appliances',
'bell',
'biomeinfo',
'callback_api',
'cottages',
'display_modpack',
'fluid_lib',
'fontwizard',
'frame',
'handle_schematics',
'maptools',
'--- quitadas por feas morelights',
'servercleaner',
'wield3d para ver que usan en la mano los otros jugadores',
'warps version de faco',
'--- retirado por falta de mantenimiento en el mod enciclopedia',
'maple',
'--- retirado por feo locks',
'facade',
'large_slurgs',
'steampunkblimp',
'nautilus',
'-- no era lo que buscaba caverrealms',
'cloudlands --editado por mi',
'-- mucho lag, todo se seca dinamic liquid',
'glowpack',
'luxury deco, --editado por mi',
'ma pops --editado por mi',
'lootcrates',
'--- quitado porque genera conflicto con mods multidimensions',
'bike',
'tresures',
'folks',
'letters',
'--no soporta un complemento de 3darmor ocular networks',
'wings --pensando en su utilidad',
'worldedge',
'christmasdeco',
'bridges',
'-- retirado genera error al tocar campana principal bellfry',
'cloudstuff',
'bees',
'vehicle mash --solo en observacion y porque cloud stuff lo rquiere',
'-- retirado contraproducente para algunas construcciones sedimentary',
'foodblocks',
'farmingflood',
'herbs',
'radiant_damage',
'witchcrat',
'player_effects',
'itemshelf',
'latency_proteccion',
'poshud lag and other info',
'--- nunca me aparecio y no le encuentro utilidad por mod de encantamiento treecapitor',
'enchantments version skamiz kazz',
'enchanting table',
)
aUsar = sorted(mods)


print("After using the mapping technique: ")
print('\n'.join(map(str, aUsar)))


